### PR TITLE
add Myanmar

### PR DESCRIPTION
**Pull request by aksharp**

### CODE REVIEW

**Comment by ericluria** [comment]
MMR is explicitly unsupported: https://github.com/flowcommerce/json-reference/blob/ab452f7692a985ff0d49f0e24384403a9c4aab73/common/common.go#L344

the real question here is why someone was able to enter it as their country in MVMT checkout if it's not available in the dropdown

**Comment by aksharp** [comment]
@paololim to confirm where new country should be added to prior to lib-reference-scala:
https://github.com/flowcommerce/json-reference/blob/master/data/cleansed/countries.json
https://github.com/flowcommerce/json-reference/blob/master/data/final/countries.json
https://github.com/flowcommerce/json-reference/blob/master/data/source/countries.csv (already here)
Did I miss anything?

**Comment by paololim** [comment]
@aksharp yes, it is explicitly not supported in code. Also, we shouldn't be adding to these scala classes in this project. These are generated. The workflow is:
- Make updates to flowcommerce/json-reference
- Run script/generate.go in this project

If the country doesn't show up in the generated class, then there's a reason it was not. A few questions:
- Why do we want Myanmar?
- If we really want it to show up as a valid country, then remove it from the blacklist of countries and regenerate the reference data again. But please do not manually update the generated classes.

**Comment by aksharp** [comment]
@paololim submitted a PR for this https://github.com/flowcommerce/json-reference/pull/35
We did get a FlowError alert that MMR was not a valid country in our ref-data from MVMT api call. The assumption is that someone in Myanmar tried to buy something from MVMT but could not. Any reason we would blacklist Myanmar? Where do we blacklist countries?

**Comment by paololim** [comment]
see comment in the other pr

**Comment by aksharp** [comment]
closing this PR due to changes to be in other project

**Pull request closed without merging**
